### ISSUE TITLE
Error while trying to fetch devices!

### ISSUE THREAD

**Issue by stimming** [peterkappelt/Tradfri-FHEM#14]
when i try to fetch my devices, i always get this error message : "Error while trying to fetch devices!". With "get coapClientVersion" i resive the message "coap-client v4.1.2 -- a small CoAP implementation".
And if i run "coap-client -m get -k PSK -u Client_identity coaps://IP/15001" in my commandline" i get this output: 
v:1 t:CON c:GET i:24f3 {} [ ]
decrypt_verify(): found 24 bytes cleartext
decrypt_verify(): found 4 bytes cleartext
4.01

i guess i did all the steps of your tutorial without any mistakes.. 

ty for your help
greetings Stimming

**Comment by peterkappelt** [comment]
There was an update for the IKEA Gateway that changed the authentication scheme a couple of months ago. A temporary fix is described in #11, at the end. I was to busy to implement a stable workaround into this software, but it will be done once.

However, I recommend using the "Beta" version. Though it is still called "Beta" it is already running stable. The authentication issue has been fixed there already. There are only some features missing before moving it into the stable branch.

**Comment by DanMittendorf** [comment]
I also tried the temporary fix #11 but it won't work.

When I run the command 
`coap-client -m post -u "Client_identity" -k "PSKCODE" -e '{"9090":"IDENTITY"}' "coaps://MYIPADDRESS:5684/15011/9063"`

All I get as a response is:
`v:1 t:CON c:POST i:78d5 {} [ ]`

Has there been another update for the IKEA Gateway so that this procedure isn't working anymore as described in #11?

**EDIT:**
Nevermind! I used the wrong IP address... My bad! Sorry.
